name: Deploy to GCP (Google Cloud Storage)

on:
  push:
    branches:
      - master  # Trigger deployment on push to master branch

jobs:
  deploy:
    runs-on: ubuntu-latest
     
    steps:
    # Step 1: Checkout the code from GitHub
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        version: '379.0.0'

    # Step 3: Authenticate with Google Cloud using the Service Account JSON key stored in GitHub Secrets
    - name: Authenticate with Google Cloud
      run: gcloud auth activate-service-account --key-file ${{ secrets.GCP_KEY }}

    # Step 4: Deploy files to Google Cloud Storage
    - name: Deploy to Google Cloud Storage
      run: |
        gsutil -m cp -r * gs://portofoliiiiiiiio/  # Replace with your bucket name
        gsutil iam ch allUsers:objectViewer gs://portofoliiiiiiiio  # Grant public access
        gsutil web set -m index.html -e 404.html gs://portofoliiiiiiiio  # Set index.html as the entry point
